name: 'Localization'
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download translations
        uses: simplelocalize/download@v2.1
        with:
          apiKey: 8b0540E5C442a6ee713c270a7dE98C648991701B81f47b9a
          downloadPath: ./{lang}/translations.json
          downloadFormat: single-language-json
